### ISSUE TITLE
error in qryn

### ISSUE THREAD

**Issue by blumamir** [odigos-io/example-qryn#2]
Hi qryn team.

When I try to run the example integration, I get the following in the cluster collector logs:

```sh
2024-10-19T06:55:26.764Z        error   exporterhelper/queue_sender.go:92       Exporting failed. Dropping data.{"kind": "exporter", "data_type": "traces", "name": "otlphttp/qryn-odigos.io.dest.qryn-oss-pxzmw", "error": "not retryable error: Permanent error: rpc error: code = Unknown desc = error exporting items, request to http://qryn-qryn-helm.qryn:3100/v1/traces responded with HTTP Status Code 500", "dropped_items": 4}
go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
        go.opentelemetry.io/collector/exporter@v0.106.0/exporterhelper/queue_sender.go:92
go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume
        go.opentelemetry.io/collector/exporter@v0.106.0/internal/queue/bounded_memory_queue.go:52
go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1
        go.opentelemetry.io/collector/exporter@v0.106.0/internal/queue/consumers.go:43
```

And these in the `qryn` pod:

```
Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    at flatVal (/app/lib/utils.js:173:29)
    at flatAttrs (/app/lib/utils.js:187:7)
    at flatOTLPAttrs (/app/lib/utils.js:191:10)
    at new module.exports (/app/lib/db/otlp.js:8:83)
    at /app/lib/db/clickhouse.js:356:32
    at Array.map (<anonymous>)
    at /app/lib/db/clickhouse.js:356:20
    at new Promise (<anonymous>)
    at pushOTLP (/app/lib/db/clickhouse.js:352:10)
    at Object.handler (/app/lib/handlers/otlp_push.js:49:9)
```

Can you please assist? probably something missing in my setup

**Comment by blumamir** [comment]
fixed in helm version `v0.1.3`
